<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\KeycapStore.Application\KeycapStore.Application.csproj" />
    <ProjectReference Include="..\KeycapStore.Infrastructure\KeycapStore.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>ce096736-8861-4f56-8346-ac82cf72a2c4</UserSecretsId>
  </PropertyGroup>

</Project>
