// <auto-generated />
using System;
using KeycapStore.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KeycapStore.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261005134256_SeedCatalog")]
    partial class SeedCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KeycapStore.Domain.Catalog.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6f1c2a7e-3b4d-4c8a-9e21-0a1b2c3d4e01"),
                            Name = "Kit Aurora (base)",
                            Price = 349.90m,
                            Stock = 40
                        },
                        new
                        {
                            Id = new Guid("6f1c2a7e-3b4d-4c8a-9e21-0a1b2c3d4e02"),
                            Name = "Kit Aurora (novelties)",
                            Price = 129.90m,
                            Stock = 3
                        },
                        new
                        {
                            Id = new Guid("6f1c2a7e-3b4d-4c8a-9e21-0a1b2c3d4e03"),
                            Name = "Kit Maré (base)",
                            Price = 319.90m,
                            Stock = 25
                        },
                        new
                        {
                            Id = new Guid("6f1c2a7e-3b4d-4c8a-9e21-0a1b2c3d4e04"),
                            Name = "Kit Maré (modificadores)",
                            Price = 149.90m,
                            Stock = 0
                        },
                        new
                        {
                            Id = new Guid("6f1c2a7e-3b4d-4c8a-9e21-0a1b2c3d4e05"),
                            Name = "Kit Zéfiro (base)",
                            Price = 299.90m,
                            Stock = 12
                        },
                        new
                        {
                            Id = new Guid("6f1c2a7e-3b4d-4c8a-9e21-0a1b2c3d4e06"),
                            Name = "Kit Zéfiro (teclas de função)",
                            Price = 89.90m,
                            Stock = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
